server:
  port: 8080

spring:
  datasource:
    # 阿里云服务器
    # url: jdbc:mysql://139.196.28.154:3306/package_manage?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    # username: kirito

    # 本地
    url: jdbc:mysql://localhost:3306/package_manage?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 054417@nufe
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid 扩展属性配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60
      # 开启 Druid 控功能
      filter:
        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
          log-slow-sql: true # 开启慢查询记录
          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
        enabled: true # 是否开启 StatViewServlet
        login-username: kirito # 账号
        login-password: kirito # 密码

  redis:
    # 阿里云服务器
    # host: 139.196.28.154

    # 本地
    host: localhost
    port: 6379
    database: 0

resources:
  static-locations: classpath:/static/,classpath:/templates/

logging:
  level:
    root: debug

mybatis:
  config-location: classpath:conf/mybatis-config.xml    # MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml              # Mapper.xml 地址
  type-aliases-package: per.kirito.pack.pojo            # 数据库实体类包路径

pagehelper:
  # 配置使用的数据库语言
  helper-dialect: mysql
  # 开启分页参数合理化功能
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true