server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.196.28.154:3306/package_manage?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: kirito
    password: 054417@nufe
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid扩展属性配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # max-evictable-idle-time-millis: 600000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60

#  jpa:
#    open-in-view: false
#    database: MySQL
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  redis:
    host: 139.196.28.154
    port: 6379
    database: 0

#mvc:
#  static-path-pattern: /**

resources:
  static-locations: classpath:/static/,classpath:/templates/

logging:
  level:
    root: debug

mybatis:
  config-location: classpath:conf/mybatis-config.xml    # MyBatis配置文件路径
  mapper-locations: classpath:mapper/*.xml              # Mapper.xml地址
  type-aliases-package: per.kirito.pack.pojo            # 数据库实体类包路径
#  configuration:
#    # 开启驼峰命名转换
#    map-underscore-to-camel-case: false

pagehelper:
  # 配置使用的数据库语言
  helper-dialect: mysql
  # 开启分页参数合理化功能
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true